(define (solve)
  (let ((sum 0))
	(let loop ((n 0))
	  (when (< n 1000)
		(set! sum (+ sum n))
		(loop (+ n 3))))
	(let loop ((n 0))
	  (when (< n 1000)
		(set! sum (+ sum n))
		(loop (+ n 5))))
	(let loop ((n 0))
	  (when (< n 1000)
		(set! sum (- sum n))
		(loop (+ n 15))))
	sum))
